learning_rate: 0.00005
batch_size: 4
gradient_accumulation_steps: 33
eval_batch_size: 4
hidden_size: 768
num_hidden_layers: 12
num_attention_heads: 12
model_flavour: "bert"
eval_steps: 500
prediction_fraction: 0.15
masking_fraction: 0.8
random_replacement_fraction: 0.1
minimum_number_of_tokens: 20
num_training_epochs: 5
max_position_embeddings: 45625
min_history_size: 20
weight_decay: 0.001
hidden_dropout_prob: 0.15
attention_probs_dropout_prob: 0.15
training_partition_size: 256
validation_partition_size: 12
early_stop_metric: "eval_loss"
early_stop_patience: 30
validation_set_fraction: 0.0015
override_maxlen: 1024
tokens_kept_fraction: 0.9995
logging_steps: 500
save_steps: 20000
bf16: False
num_dataloader_workers: 0
fp16: False
warmup_steps: 0.05
save_total_limit: 3
early_stopping_delay: 0.0
output: "outputs/pretrain_truncated_before_E08_E09_E10_E11/"
training_data_filepath: "datasets/synthea_diabetes_training_updated_truncated_before_E08_E09_E10_E11.parquet"
val_size: 0.01
vocab_filepath: "datasets/vocab_synthea.txt"
